
name: argocd-sync

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/skip-based-on-commit-message#just-use-yaml-recommended
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Install argocd and run `app sync`
      run: |
        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

        # /!\ error with argocd app sync
        # https://github.com/argoproj/argo-cd/issues/5592#issuecomment-949083289
        # argocd app sync app-staging --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }} --insecure

        # workaround
        argocd app get app-staging --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }} --insecure --grpc-web --refresh >/dev/null
        argocd app wait app-staging --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }} --insecure --grpc-web --sync --health

        argocd app get app-production --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }} --insecure --grpc-web --refresh >/dev/null
        argocd app wait app-production --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }} --insecure --grpc-web --sync --health
